filler="="*31
print(filler)
print("= 1.- Euros a Dolars")
print("= 2.- Euros a Yens")
print("= 3.- Dolars a Euros")
print("= 4.- Dolars a Yens")
print("= 5.- Yens a Euros")
print("= 6.- Yens a Dolars")
print(filler)
print("= Tria una opció de conversió =")
print(filler)